Repository hmcts/adoption-backend, pull requests merged in 2020-02, with the labels that each got.

#4 feat: terraform scripts
  Jenkinsfile_CNP
  bin/configurer/utils/wait-for.sh
  build.gradle
  infrastructure/aat.tfvars
  infrastructure/demo.tfvars
  infrastructure/main.tf
  infrastructure/output.tf
  infrastructure/state.tf
  infrastructure/variables.tf
  src/main/java/uk/gov/hmcts/reform/adoption/controllers/RootController.java
Labels: ns:adoption, rel:adoption-backend-pr-4

#6 FPLA-1325 terraform warnings fix and add missing variable
  infrastructure/main.tf
  infrastructure/variables.tf
Labels: ns:adoption, rel:adoption-backend-pr-6

#7 fix: Terraform warnings fixes
  infrastructure/main.tf
  infrastructure/state.tf
Labels: ns:adoption, rel:adoption-backend-pr-7

#10 Dev/downgrade terraform
  infrastructure/.terraform-version
  infrastructure/main.tf
  infrastructure/variables.tf
Labels: ns:adoption, rel:adoption-backend-pr-10

#11 fix: terraform downgrade and locking down azurerm provider to specific version
  infrastructure/.terraform-version
  infrastructure/main.tf
Labels: ns:adoption, rel:adoption-backend-pr-11

#13 fix: include smoke test directory
  build.gradle
  config/owasp/suppressions.xml
  src/smokeTest/java/uk/gov/hmcts/reform/adoption/SmokeTest.java
Labels: ns:adoption, rel:adoption-backend-pr-13

#14 feat:Deploy ccd stack in preview environment (FPLA-1357)
  Jenkinsfile_CNP
  charts/adoption-backend/Chart.yaml
  charts/adoption-backend/requirements.yaml
  charts/adoption-backend/values.preview.template.yaml
  charts/adoption-backend/values.yaml
Labels: ns:adoption, rel:adoption-backend-pr-14

#19 fix: prefer staging url
  Jenkinsfile_CNP
Labels: ns:adoption, rel:adoption-backend-pr-19

#15 fix: chart updates to reflect versioning in cnp-flux-config
  charts/adoption-backend/Chart.yaml
  charts/adoption-backend/values.yaml
Labels: ns:adoption, rel:adoption-backend-pr-15
